// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Black Arrow documents
 */
interface ArrowDocumentData {
  /**
   * Arrow field in *Black Arrow*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: arrow.arrow
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  arrow: prismic.ImageField<never>;
}

/**
 * Black Arrow document from Prismic
 *
 * - **API ID**: `arrow`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArrowDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<ArrowDocumentData>, "arrow", Lang>;

/**
 * Item in *Dashboard → Sidebar*
 */
export interface DashboardDocumentDataSidebarItem {
  /**
   * Label field in *Dashboard → Sidebar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dashboard.sidebar[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

type DashboardDocumentDataSlicesSlice = never;

/**
 * Content for Dashboard documents
 */
interface DashboardDocumentData {
  /**
   * Sidebar field in *Dashboard*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: dashboard.sidebar[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  sidebar: prismic.GroupField<Simplify<DashboardDocumentDataSidebarItem>>;

  /**
   * Slice Zone field in *Dashboard*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: dashboard.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<DashboardDocumentDataSlicesSlice> /**
   * Meta Title field in *Dashboard*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: dashboard.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Dashboard*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: dashboard.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Dashboard*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: dashboard.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Dashboard document from Prismic
 *
 * - **API ID**: `dashboard`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DashboardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DashboardDocumentData>,
    "dashboard",
    Lang
  >;

/**
 * Item in *Discover → Search params*
 */
export interface DiscoverDocumentDataSearchParamsItem {
  /**
   * identifier field in *Discover → Search params*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: discover.search_params[].identifier
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  identifier: prismic.KeyTextField;

  /**
   * Label field in *Discover → Search params*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Artist
   * - **API ID Path**: discover.search_params[].label
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  label: prismic.RichTextField;
}

type DiscoverDocumentDataSlicesSlice = never;

/**
 * Content for Discover documents
 */
interface DiscoverDocumentData {
  /**
   * Title field in *Discover*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: discover.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Search params field in *Discover*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: discover.search_params[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  search_params: prismic.GroupField<
    Simplify<DiscoverDocumentDataSearchParamsItem>
  >;

  /**
   * Discover Description field in *Discover*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: discover.discover_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  discover_description: prismic.RichTextField;

  /**
   * No User Text field in *Discover*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: discover.no_user_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  no_user_text: prismic.RichTextField;

  /**
   * Slice Zone field in *Discover*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: discover.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<DiscoverDocumentDataSlicesSlice> /**
   * Meta Title field in *Discover*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: discover.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Discover*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: discover.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Discover*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: discover.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Discover document from Prismic
 *
 * - **API ID**: `discover`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DiscoverDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DiscoverDocumentData>,
    "discover",
    Lang
  >;

/**
 * Item in *FAQ → Categories*
 */
export interface FaqDocumentDataCategoriesItem {
  /**
   * Title field in *FAQ → Categories*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.categories[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Identifier field in *FAQ → Categories*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.categories[].identifier
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  identifier: prismic.KeyTextField;
}

type FaqDocumentDataSlicesSlice = never;

/**
 * Content for FAQ documents
 */
interface FaqDocumentData {
  /**
   * Title field in *FAQ*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Categories field in *FAQ*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.categories[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  categories: prismic.GroupField<Simplify<FaqDocumentDataCategoriesItem>>;

  /**
   * Slice Zone field in *FAQ*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<FaqDocumentDataSlicesSlice> /**
   * Meta Title field in *FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: faq.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: faq.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *FAQ*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * FAQ document from Prismic
 *
 * - **API ID**: `faq`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<FaqDocumentData>, "faq", Lang>;

/**
 * Content for FAQ Item documents
 */
interface FaqItemDocumentData {
  /**
   * Index field in *FAQ Item*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_item.index
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  index: prismic.NumberField;

  /**
   * Title field in *FAQ Item*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_item.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Belongs to field in *FAQ Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_item.belongs_to
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  belongs_to: prismic.KeyTextField;

  /**
   * Description field in *FAQ Item*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_item.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * FAQ Item document from Prismic
 *
 * - **API ID**: `faq_item`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqItemDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FaqItemDocumentData>,
    "faq_item",
    Lang
  >;

/**
 * Item in *Global Search Genres → Genres*
 */
export interface GlobalSearchGenresDocumentDataGenresItem {
  /**
   * Item field in *Global Search Genres → Genres*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: global_search_genres.genres[].item
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  item: prismic.KeyTextField;
}

/**
 * Content for Global Search Genres documents
 */
interface GlobalSearchGenresDocumentData {
  /**
   * Genres field in *Global Search Genres*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: global_search_genres.genres[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  genres: prismic.GroupField<
    Simplify<GlobalSearchGenresDocumentDataGenresItem>
  >;
}

/**
 * Global Search Genres document from Prismic
 *
 * - **API ID**: `global_search_genres`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalSearchGenresDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalSearchGenresDocumentData>,
    "global_search_genres",
    Lang
  >;

/**
 * Item in *Homepage → icon bar*
 */
export interface HomepageDocumentDataIconBarItem {
  /**
   * icon field in *Homepage → icon bar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.icon_bar[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;
}

type HomepageDocumentDataSlicesSlice = never;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Catchphrase field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.catchphrase
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  catchphrase: prismic.RichTextField;

  /**
   * Description field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Analyze Field Description field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.analyze_field_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  analyze_field_description: prismic.RichTextField;

  /**
   * icon bar field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.icon_bar[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  icon_bar: prismic.GroupField<Simplify<HomepageDocumentDataIconBarItem>>;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type LoginDocumentDataSlicesSlice = never;

/**
 * Content for Login documents
 */
interface LoginDocumentData {
  /**
   * Title field in *Login*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: login.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *Login*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: login.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Sign up instead field in *Login*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: login.sign_up_instead
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sign_up_instead: prismic.RichTextField;

  /**
   * Slice Zone field in *Login*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: login.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LoginDocumentDataSlicesSlice> /**
   * Meta Title field in *Login*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: login.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Login*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: login.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Login*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: login.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Login document from Prismic
 *
 * - **API ID**: `login`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LoginDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<LoginDocumentData>, "login", Lang>;

/**
 * Content for Login Button documents
 */
interface LoginButtonDocumentData {
  /**
   * Text field in *Login Button*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Log In
   * - **API ID Path**: login_button.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Login Button document from Prismic
 *
 * - **API ID**: `login_button`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LoginButtonDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LoginButtonDocumentData>,
    "login_button",
    Lang
  >;

/**
 * Content for Logo documents
 */
interface LogoDocumentData {
  /**
   * Logo field in *Logo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Logo document from Prismic
 *
 * - **API ID**: `logo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LogoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<LogoDocumentData>, "logo", Lang>;

type LogoutSuccessDocumentDataSlicesSlice = never;

/**
 * Content for Logout Success documents
 */
interface LogoutSuccessDocumentData {
  /**
   * Logout Was Successful field in *Logout Success*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logout_success.logout_was_successful
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  logout_was_successful: prismic.RichTextField;

  /**
   * Redirect field in *Logout Success*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logout_success.redirect
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  redirect: prismic.RichTextField;

  /**
   * Slice Zone field in *Logout Success*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: logout_success.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LogoutSuccessDocumentDataSlicesSlice> /**
   * Meta Title field in *Logout Success*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: logout_success.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Logout Success*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: logout_success.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Logout Success*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logout_success.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Logout Success document from Prismic
 *
 * - **API ID**: `logout_success`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LogoutSuccessDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LogoutSuccessDocumentData>,
    "logout_success",
    Lang
  >;

/**
 * Content for Media Player Icons documents
 */
interface MediaPlayerIconsDocumentData {
  /**
   * Play Button field in *Media Player Icons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_player_icons.play_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  play_button: prismic.ImageField<never>;

  /**
   * Pause Button field in *Media Player Icons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_player_icons.pause_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  pause_button: prismic.ImageField<never>;

  /**
   * Play Button Transparent field in *Media Player Icons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_player_icons.play_button_transparent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  play_button_transparent: prismic.ImageField<never>;

  /**
   * Pause Button Transparent field in *Media Player Icons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_player_icons.pause_button_transparent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  pause_button_transparent: prismic.ImageField<never>;
}

/**
 * Media Player Icons document from Prismic
 *
 * - **API ID**: `media_player_icons`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MediaPlayerIconsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MediaPlayerIconsDocumentData>,
    "media_player_icons",
    Lang
  >;

/**
 * Item in *Navigation → Items*
 */
export interface NavigationDocumentDataItemsItem {
  /**
   * Link field in *Navigation → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Navigation → Socials Links*
 */
export interface NavigationDocumentDataSocialsLinksItem {
  /**
   * Link field in *Navigation → Socials Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.socials_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Icon field in *Navigation → Socials Links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.socials_links[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Items field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<NavigationDocumentDataItemsItem>>;

  /**
   * Socials Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.socials_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  socials_links: prismic.GroupField<
    Simplify<NavigationDocumentDataSocialsLinksItem>
  >;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

/**
 * Content for Placeholder Image Track documents
 */
interface PlaceholderImageTrackDocumentData {
  /**
   * Placeholder Image Track field in *Placeholder Image Track*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: placeholder_image_track.placeholder_image_track
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  placeholder_image_track: prismic.ImageField<never>;
}

/**
 * Placeholder Image Track document from Prismic
 *
 * - **API ID**: `placeholder_image_track`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PlaceholderImageTrackDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PlaceholderImageTrackDocumentData>,
    "placeholder_image_track",
    Lang
  >;

type ReplaceIconDocumentDataSlicesSlice = never;

/**
 * Content for Replace Icon documents
 */
interface ReplaceIconDocumentData {
  /**
   * Replace Icon field in *Replace Icon*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: replace_icon.replace_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  replace_icon: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Replace Icon*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: replace_icon.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ReplaceIconDocumentDataSlicesSlice> /**
   * Meta Title field in *Replace Icon*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: replace_icon.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Replace Icon*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: replace_icon.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Replace Icon*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: replace_icon.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Replace Icon document from Prismic
 *
 * - **API ID**: `replace_icon`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReplaceIconDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ReplaceIconDocumentData>,
    "replace_icon",
    Lang
  >;

type SearchDocumentDataSlicesSlice = never;

/**
 * Content for Search  documents
 */
interface SearchDocumentData {
  /**
   * No Results text field in *Search *
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: search.no_results_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  no_results_text: prismic.RichTextField;

  /**
   * Search Results Title field in *Search *
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: search.search_results_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  search_results_title: prismic.RichTextField;

  /**
   * Slice Zone field in *Search *
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: search.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SearchDocumentDataSlicesSlice> /**
   * Meta Title field in *Search *
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: search.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Search *
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: search.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Search *
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: search.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Search  document from Prismic
 *
 * - **API ID**: `search`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SearchDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SearchDocumentData>,
    "search",
    Lang
  >;

type SettingsDocumentDataSlicesSlice = never;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Slice Zone field in *Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice> /**
   * Meta Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: settings.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: settings.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

/**
 * Content for Social Icons documents
 */
interface SocialIconsDocumentData {
  /**
   * Icon field in *Social Icons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_icons.icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Social Icons document from Prismic
 *
 * - **API ID**: `social_icons`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialIconsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SocialIconsDocumentData>,
    "social_icons",
    Lang
  >;

type UserAvatarDocumentDataSlicesSlice = never;

/**
 * Content for User Avatar documents
 */
interface UserAvatarDocumentData {
  /**
   * User Avatar field in *User Avatar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: user_avatar.user_avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  user_avatar: prismic.ImageField<never>;

  /**
   * Slice Zone field in *User Avatar*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: user_avatar.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<UserAvatarDocumentDataSlicesSlice> /**
   * Meta Title field in *User Avatar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: user_avatar.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *User Avatar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: user_avatar.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *User Avatar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: user_avatar.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * User Avatar document from Prismic
 *
 * - **API ID**: `user_avatar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type UserAvatarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<UserAvatarDocumentData>,
    "user_avatar",
    Lang
  >;

/**
 * Content for White Arrow documents
 */
interface WhiteArrowDocumentData {
  /**
   * White Arrow field in *White Arrow*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: white_arrow.white_arrow
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  white_arrow: prismic.ImageField<never>;
}

/**
 * White Arrow document from Prismic
 *
 * - **API ID**: `white_arrow`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WhiteArrowDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<WhiteArrowDocumentData>,
    "white_arrow",
    Lang
  >;

export type AllDocumentTypes =
  | ArrowDocument
  | DashboardDocument
  | DiscoverDocument
  | FaqDocument
  | FaqItemDocument
  | GlobalSearchGenresDocument
  | HomepageDocument
  | LoginDocument
  | LoginButtonDocument
  | LogoDocument
  | LogoutSuccessDocument
  | MediaPlayerIconsDocument
  | NavigationDocument
  | PlaceholderImageTrackDocument
  | ReplaceIconDocument
  | SearchDocument
  | SettingsDocument
  | SocialIconsDocument
  | UserAvatarDocument
  | WhiteArrowDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArrowDocument,
      ArrowDocumentData,
      DashboardDocument,
      DashboardDocumentData,
      DashboardDocumentDataSidebarItem,
      DashboardDocumentDataSlicesSlice,
      DiscoverDocument,
      DiscoverDocumentData,
      DiscoverDocumentDataSearchParamsItem,
      DiscoverDocumentDataSlicesSlice,
      FaqDocument,
      FaqDocumentData,
      FaqDocumentDataCategoriesItem,
      FaqDocumentDataSlicesSlice,
      FaqItemDocument,
      FaqItemDocumentData,
      GlobalSearchGenresDocument,
      GlobalSearchGenresDocumentData,
      GlobalSearchGenresDocumentDataGenresItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataIconBarItem,
      HomepageDocumentDataSlicesSlice,
      LoginDocument,
      LoginDocumentData,
      LoginDocumentDataSlicesSlice,
      LoginButtonDocument,
      LoginButtonDocumentData,
      LogoDocument,
      LogoDocumentData,
      LogoutSuccessDocument,
      LogoutSuccessDocumentData,
      LogoutSuccessDocumentDataSlicesSlice,
      MediaPlayerIconsDocument,
      MediaPlayerIconsDocumentData,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataItemsItem,
      NavigationDocumentDataSocialsLinksItem,
      PlaceholderImageTrackDocument,
      PlaceholderImageTrackDocumentData,
      ReplaceIconDocument,
      ReplaceIconDocumentData,
      ReplaceIconDocumentDataSlicesSlice,
      SearchDocument,
      SearchDocumentData,
      SearchDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataSlicesSlice,
      SocialIconsDocument,
      SocialIconsDocumentData,
      UserAvatarDocument,
      UserAvatarDocumentData,
      UserAvatarDocumentDataSlicesSlice,
      WhiteArrowDocument,
      WhiteArrowDocumentData,
      AllDocumentTypes,
    };
  }
}
