import type { Metadata } from 'next';
import './globals.css';

import MainNavigation from '@/components/shared/MainMenu';

import { createClient } from '@/prismicio';
import { Providers } from '@/providers/Providers';
import BackgroundContainer from '@/components/shared/BackgroundContainer';

import SoundcloudPlayer from '@/components/set/SoundcloudPlayer';
import MiniPlayer from '@/components/player/MiniPlayer';

import TrackAudioPlayer from '@/components/player/TrackAudioPlayer';
import DocumentTitle from '@/components/shared/DocumentTitle';

export const metadata: Metadata = {
  title: '404Hz',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const client = createClient();
  const placeholderImageSong = await client
    .getSingle('placeholder_image_track')
    .catch(() => null);
  const icons = await client.getAllByType('social_icons');
  const mediaPlayerIcons = await client.getSingle('media_player_icons');
  const blackArrow = await client.getSingle('arrow');
  const whiteArrow = await client.getSingle('white_arrow');
  const logo = await client.getSingle('logo');

  const imageContextProps = {
    placeholderImageSong: placeholderImageSong,
    blackArrow: blackArrow,
    whiteArrow: whiteArrow,
    logo: logo
  };

  return (
    <html lang="en">
      <body>
        <DocumentTitle />
        <BackgroundContainer />
        <Providers
          icons={icons}
          imageContextProps={imageContextProps}
          mediaPlayerIcons={mediaPlayerIcons}
        >
          <SoundcloudPlayer />
          <TrackAudioPlayer />
          <MiniPlayer />
          <MainNavigation />
          {children}{' '}
        </Providers>
      </body>
    </html>
  );
}
